### PR TITLE
method name change

### PR DESCRIPTION
**Pull request by maxstudener**
Good times with newrelic

### CODE REVIEW

**Comment by maxstudener** [comment]
Related to https://github.com/wvanbergen/newrelic-vertica/issues/2

**Comment by wvanbergen** [comment]
What version of the newrelic gem are you using?

**Comment by maxstudener** [comment]
newrelic_rpm (3.13.1.300)

**Comment by wvanbergen** [comment]
Thanks! Released as version 0.0.4.

**Pull request merged**
